import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header className="bg-white shadow">
        <div className="container mx-auto px-4 py-6 flex justify-between items-center">
          <div className="logo flex items-center">
          <Image src="/images/logo.png" width={100} height={100}></Image>
          <h1 className="text-xl font-bold">Infinite Maya Labs</h1>
          </div>
          <nav>
            <a href="/" className="px-4">Home</a>
            <a href="/games" className="px-4">Games</a>
            <a href="/about" className="px-4">About</a>
            <a href="#" className="px-4">Contact</a>
          </nav>
        </div>
      </header>
        {children}</body>
    </html>
  );
}
